In [1]:
# BOW implementation using NLTK

In [9]:
import pandas as pd

In [14]:
pd.read_csv(r"C:\Users\FINRISE\Desktop\Django\mygenai\spam.csv", encoding='latin1')

        v1  ... Unnamed: 4
0      ham  ...        NaN
1      ham  ...        NaN
2     spam  ...        NaN
3      ham  ...        NaN
4      ham  ...        NaN
...    ...  ...        ...
5567  spam  ...        NaN
5568   ham  ...        NaN
5569   ham  ...        NaN
5570   ham  ...        NaN
5571   ham  ...        NaN

[5572 rows x 5 columns]

In [20]:
pd.read_csv(r"C:\Users\FINRISE\Desktop\Django\mygenai\spam.csv", encoding='latin1',usecols=[0,1],names=["label","message"],header=0)

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [21]:
messages = pd.read_csv(r"C:\Users\FINRISE\Desktop\Django\mygenai\spam.csv", encoding='latin1',usecols=[0,1],names=["label","message"],header=0)

In [22]:
messages

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [26]:
## Data cleaning and preprocessing 

import re
import nltk
nltk.download('stopwords')   # Download stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\FINRISE\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [27]:
from nltk.corpus import stopwords
from  nltk.stem.porter import PorterStemmer
PorterStemmer = PorterStemmer()

In [32]:
corpus = []
for i in range(0,len(messages)):
    review = re.sub('[^a-zA-z]','',messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [PorterStemmer.stem(word) for word in review if word not in stopwords.words('english')]
    review = ''.join(review)
    corpus.append(review)

In [33]:
corpus

['gountiljurongpointcrazyavailableonlyinbugisngreatworldlaebuffetcinetheregotamorewat',
 'oklarjokingwifuoni',
 'freeentryinawklycomptowinfacupfinaltktsstmaytextfatotoreceiveentryquestionstdtxtratetcsapplyov',
 'udunsaysoearlyhorucalreadythensay',
 'nahidontthinkhegoestousfhelivesaroundherethough',
 'freemsgheytheredarlingitsbeenweeksnowandnowordbackidlikesomefunyouupforitstilltbokxxxstdchgstosendtorcv',
 'evenmybrotherisnotliketospeakwithmetheytreatmelikeaidspat',
 'asperyourrequestmellemelleoruminnaminungintenurunguvettamhasbeensetasyourcallertuneforallcallerspresstocopyyourfriendscallertun',
 'winnerasavaluednetworkcustomeryouhavebeenselectedtoreceiveaprizerewardtoclaimcallclaimcodeklvalidhoursonli',
 'hadyourmobilemonthsormoreurentitledtoupdatetothelatestcolourmobileswithcameraforfreecallthemobileupdatecofreeon',
 'imgonnabehomesoonandidontwanttotalkaboutthisstuffanymoretonightkivecriedenoughtoday',
 'sixchancestowincashfromtopoundstxtcshandsendtocostpdaydaystsandcsapplyreplyhlinfo',
 'urgentyouhavewonaweekfreemembershipinourprizejackpottxtthewordclaimtonotcwwwdbuknetlccltdpoboxldnwarw',
 'ivebeensearchingfortherightwordstothankyouforthisbreatheripromiseiwonttakeyourhelpforgrantedandwillfulfilmypromiseyouhavebeenwonderfulandablessingatalltim',
 'ihaveadateonsundaywithwil',
 'xxxmobilemovieclubtouseyourcreditclickthewaplinkinthenexttxtmessageorclickherehttpwapxxxmobilemovieclubcomnqjkgighjjgcbl',
 'ohkimwatchingher',
 'ehurememberhowspellhisnameyesididhevnaughtymakeuntilivwet',
 'fineifthatsthewayufeelthatsthewayitsgotab',
 'englandvmacedoniadontmissthegoalsteamnewstxturnationalteamtoegenglandtotrywalesscotlandtxtpoboxoxwwq',
 'isthatseriouslyhowyouspellhisnam',
 'imgoingtotryformonthshahaonlyjok',
 'so_payfirstlarthenwhenisdastockcomin',
 'aftifinishmylunchthenigostrdownlorardsmthlorufinishurlunchalreadi',
 'ffffffffffalrightnowayicanmeetupwithyousoon',
 'justforcedmyselftoeatasliceimreallynothungrythothissucksmarkisgettingworriedheknowsimsickwheniturndownpizzalol',
 'lolyouralwayssoconvinc',
 'didyoucatchthebusareyoufryinganeggdidyoumakeateaareyoueatingyourmomsleftoverdinnerdoyoufeelmylov',
 'imbackampwerepackingthecarnowillletyouknowiftheresroom',
 'ahhhworkivaguelyrememberthatwhatdoesitfeellikelol',
 'waitthatsstillnotallthatclearwereyounotsureaboutmebeingsarcasticorthatthatswhyxdoesntwanttolivewithu',
 'yeahhegotinatandwasvapologeticnhadfallenoutandshewasactinlikespoiltchildandhegotcaughtupinthattillbutwewontgotherenotdoingtoobadlycheersy',
 'ktellmeanythingabouty',
 'forfearoffaintingwiththeofallthathouseworkyoujustdidquickhaveacuppa',
 'thanksforyoursubscriptiontoringtoneukyourmobilewillbechargedmonthpleaseconfirmbyreplyingyesornoifyoureplynoyouwillnotbecharg',
 'yupokigohomelookatthetimingsthenimsg_againxuhuigoingtolearnonndmaytoobutherlessonisatam',
 'oopsillletyouknowwhenmyroommatesdon',
 'iseetheletterbonmycar',
 'anythinglorudecid',
 'hellohowsyouandhowdidsaturdaygoiwasjusttextingtoseeifyouddecidedtodoanythingtomonotthatimtryingtoinvitemyselforanyth',
 'plsgoaheadwithwattsijustwantedtobesuredohaveagreatweekendabiola',
 'didiforgettotellyouiwantyouineedyouicraveyoubutmostofalliloveyoumysweetarabiansteedmmmmmmyummi',
 'rodgerburnsmsgwetriedtocallyoureyourreplytooursmsforafreenokiamobilefreecamcorderpleasecallnowfordeliverytomorrow',
 'whoareyouse',
 'greatihopeyoulikeyourmanwellendowediamltgtinch',
 'nocallsmessagesmissedcal',
 'didntyougethepbimmunisationinnigeria',
 'fairenoughanythinggoingon',
 'yeahhopefullyiftylercantdoiticouldmaybeaskaroundabit',
 'udontknowhowstubborniamididntevenwanttogotothehospitalikepttellingmarkimnotaweaksuckerhospitalsareforweaksuck',
 'whatyouthinkedaboutmefirsttimeyousawmeinclass',
 'agramusuallyrunslikeltgtahalfeighthissmarterthoughandgetsyoualmostawholesecondgramforltgt',
 'kfyixhasarideearlytomorrowmorningbuthescrashingatourplacetonight',
 'wowineverrealizedthatyouweresoembarassedbyyouraccomodationsithoughtyoulikeditsinceiwasdoingthebesticouldandyoualwaysseemedsohappyabout\\thecave\\imsorryididntanddonthavemoretogiveimsorryiofferedimsorryyourroomwassoembarass',
 'smsacsptvthenewjerseydevilsandthedetroitredwingsplayicehockeycorrectorincorrectendreplyendsptv',
 'doyouknowwhatmallikasherawatdidyesterdayfindoutnowlturlgt',
 'congratsyearspecialcinemapassforisyourscallnowcsuprmanvmatrixstarwarsetcallfreebxipwepmdontmissout',
 'sorryillcalllaterinmeet',
 'tellwhereyoureach',
 'yesgautiandsehwagoutofodiseri',
 'yourgonnahavetopickupaburgerforyourselfonyourwayhomeicantevenmovepainiskillingm',
 'hahahagoodjokegirlsaresituationseek',
 'itsapartofcheckingiq',
 'sorrymyroommatestookforeveritokificomebynow',
 'oklaridoublecheckwifdahairdresseralreadyhesaidwuncutvshorthesaidwillcutuntililooknic',
 'asavaluedcustomeriampleasedtoadviseyouthatfollowingrecentreviewofyourmobnoyouareawardedwithabonusprizecal',
 'todayis\\songdedicatedday\\whichsongwilludedicateformesendthistoallurvaluablefrndsbutfirstrplym',
 'urgenturawardedacomplimentarytriptoeurodisinctravacoentryortoclaimtxtdistomorefrmmobshracomorsglsupltlsaj',
 'didyouhearaboutthenew\\divorcebarbie\\itcomeswithallofkensstuff',
 'iplanetogiveonthismonthend',
 'wahluckymanthencansavemoneyhe',
 'finishedclasswherearey',
 'hibabeimathomenowwannadosomethingxx',
 'kkwhereareyouhowdidyouperform',
 'ucancallmenow',
 'iamwaitingmachancallmeonceyoufre',
 'thatscooliamagentlemanandwilltreatyouwithdignityandrespect',
 'ilikeyoupeoplesverymuchbutamveryshypa',
 'doesnotoperateafterltgtorwhat',
 'itsnotthesameherestilllookingforajobhowmuchdotasearnther',
 'sorryillcalllat',
 'kdidyoucallmejustnowah',
 'okiamonthewaytohomehihi',
 'youwillbeintheplaceofthatman',
 'yupnextstop',
 'icallyoulaterdonthavenetworkifurgntsmsm',
 'forrealwhenugettingonyoionlyneedmoreticketsandonemorejacketandimdoneialreadyusedallmymulti',
 'yesistartedtosendrequeststomakeitbutpaincamebacksoimbackinbeddoublecoinsatthefactorytooigottacashinallmynitro',
 'imreallynotuptoitstilltonightbab',
 'elakanoildownloadcomewenurfre',
 'yeahdodontstandtoclosethoyoullcatchsometh',
 'sorrytobeapainisitokifwemeetanothernightispentlateafternoonincasualtyandthatmeansihaventdoneanyofystuffmoroandthatincludesallmytimesheetsandthatsorri',
 'smileinpleasuresmileinpainsmilewhentroublepourslikerainsmilewhensumhurtsusmilebecozsomeonestilllovestoseeusmil',
 'pleasecallourcustomerservicerepresentativeonbetweenampmasyouhavewonaguaranteedcashorpr',
 'haventplanningtobuylatericheckalreadylidoonlygotshowineafternoonufinishworkalreadi',
 'yourfreeringtoneiswaitingtobecollectedsimplytextthepassword\\mix\\totoverifygetusherandbritneyfml',
 'watchingtelugumoviewatabtu',
 'iseewhenwefinishwehaveloadsofloanstopay',
 'hiwkbeenokonholsnowyesonforabitofarunforgotthatihavehairdressersappointmentatfoursoneedtogethomenshowerbeforehanddoesthatcauseprobforu\\ham',
 'pleasedonttextmeanymoreihavenothingelsetosay',
 'okaynameurpriceaslongasitslegalwencanipickthemupyuavexamsxx',
 'imstilllookingforacartobuyandhavenotgonethedrivingtestyet',
 'asperyourrequestmellemelleoruminnaminungintenurunguvettamhasbeensetasyourcallertuneforallcallerspresstocopyyourfriendscallertun',
 'wowyourerightididntmeantodothatiguessonceigaveuponbostonmenandchangedmysearchlocationtonycsomethingchangedcuzonmysigninpageitstillsaysboston',
 'ummamylifeandvavaummaloveyoulotdear',
 'thanksalotforyourwishesonmybirthdaythanksyouformakingmybirthdaytrulymemor',
 'aightillhityouupwhenigetsomecash',
 'howwouldmyipaddresstestthatconsideringmycomputerisntaminecraftserv',
 'iknowgrumpyoldpeoplemymomwaslikeyoubetternotbelyingthenagainiamalwaystheonetoplayjok',
 'dontworryiguesshesbusi',
 'whatisthepluralofthenounresearch',
 'goingfordinnermsgyouaft',
 'imokwifitcosiliketrynewthingsbutiscaredudunlikemahcosusaidnottooloud',
 'gentwearetryingtocontactyoulastweekendsdrawshowsthatyouwonaprizeguaranteedcallclaimcodekvalidhrsonlyppm',
 'wauropeninsentenceveryformalanywayimfinetoojuzttimeatintoomuchnputtinonweighthahasoanythinspecialhappen',
 'asienteredmycabinmypasaidhappybdaybossifeltspecialsheaskdmelunchafterlunchsheinvitedmetoherapartmentwewentther',
 'youareawinneruhavebeenspeciallyselectedreceiveoraholidayflightsincspeaktoaliveoperatorclaimpmin',
 'goodoyeswemustspeakfridayeggpotatoratiofortortillaneed',
 'hmmmyunclejustinformedmethathespayingtheschooldirectlysoplsbuyfood',
 'privateyouraccountstatementforshowsunredeemedbonuspointstoclaimcallidentifiercodeexpir',
 'urgentyourmobilenowasawardedbonuscallerprizeonthisisourfinaltrytocontactucallfromlandlineboxwrcppm',
 'hereismynewaddressapplespairsallthatmalarki',
 'todaysvodanumbersendingareselectedtoreceiveaawardifyouhaveamatchpleasecallquotingclaimcodestandardratesapp',
 'iamgoingtosaomutodaywillbedoneonlyat',
 'predictwattime_llfinishbuy',
 'goodstuffwilldo',
 'justsothatyouknowyetundehasntsentmoneyyetijustsentheratextnottobothersendingsoitsoveryoudonthavetoinvolveyourselfinanythingishouldnthaveimposedanythingonyouinthefirstplacesoforthatiapologis',
 'areyouthereinroom',
 'heygirlhowruhopeurwellmeandelrbakagainlongtimenocgivemeacallsumtimefromlucyxx',
 'kkhowmuchdoesitcost',
 'imhom',
 'dearwillcalltmorrowplsaccomod',
 'firstanswermyquest',
 'sunshinequizwklyqwinatopsonydvdplayerifuknowwhichcountrythealgarveisintxtansrtosptyron',
 'wantgetlaidtonightwantrealdogginglocationssentdirecturmobjointheukslargestdoggingnetworkbttxtinggraveltontecapmsgp',
 'ionlyhafmsnitsyijuehotmailcom',
 'heisthereyoucallandmeethim',
 'nonoiwillcheckallroomsbeforact',
 'youllnotrcvanymoremsgsfromthechatsvcforfreehardcoreservicestextgotoifugetnothingumustageverifywithyrnetworktryagain',
 'gotcilazytotypeiforgot_inlectisawapouchbutlikenotvnic',
 'ktextmewhenyoureontheway',
 'sirwaitingforyourmail',
 'aswtthought\\nvergettiredofdoinglittlethingslovablepersons\\cozsomtimesthoselittlethingsoccupydbiggestpartintheirheartsgudni',
 'iknowyouarecanyouplsopentheback',
 'yesseeyanotonthedot',
 'whatsthestaffnamewhoistakingclassforu',
 'freemsgwhyhaventyourepliedtomytextimrandysexyfemaleandlivelocalluvtohearfromunetcollexltdppermsgreplystoptoend',
 'ummmawillcallaftercheckinourlifewillbeginfromqatarsoplsprayveryhard',
 'kideletedmycontactthatwhi',
 'sindugotjobinbirlasoft',
 'thewineisflowingandimihavenev',
 'yupithkcineisbettercosnoneedgodownplazamah',
 'okurtypicalrepli',
 'asperyourrequestmellemelleoruminnaminungintenurunguvettamhasbeensetasyourcallertuneforallcallerspresstocopyyourfriendscallertun',
 'youareeverywheredirtonthefloorthewindowsevenonmyshirtandsometimeswheniopenmymouthyouareallthatcomesflowingoutidreamofmyworldwithoutyouthenhalfmychoresareouttooatimeofjoyformelotsoftvshowsillseebutiguesslikeallthingsyoujustmustexistlikerainhailandmistandwhenmytimehereisdoneyouandibecomeon',
 'aaoooorightareyouatwork',
 'imleavingmyhousenow',
 'hellomylovewhatareyoudoingdidyougettothatinterviewtodayareyouyouhappyareyoubeingagoodboydoyouthinkofmeareyoumissingm',
 'customerserviceannoncementyouhaveanewyearsdeliverywaitingforyoupleasecallnowtoarrangedeliveri',
 'youareawinneruhavebeenspeciallyselectedreceivecashoraholidayflightsincspeaktoaliveoperatorclaim',
 'keepyourselfsafeformebecauseineedyouandimissyoualreadyandienvyeveryonethatseesyouinreallif',
 'newcarandhouseformyparentsihaveonlynewjobinhand',
 'imsoinlovewithyouimexcitedeachdayispendwithyouyoumakemesohappi',
 'plsstopbootydeliousfisinvitingyoutobeherfriendreplyyesornoseeherwwwsmsacubootydeliousstopsendstopfrndto',
 'bangbabesurorderisonthewayushouldreceiveaservicemsgdownloadurcontentifudonotgotowapbangbtvonurmobileinternetservicemenu',
 'iplaceallurpointsoneculturesmodulealreadi',
 'urgentwearetryingtocontactyoulastweekendsdrawshowsthatyouhavewonaprizeguaranteedcallclaimcodesvalidhrsonli',
 'hifrndwhichisbestwaytoavoidmissunderstdingwitourbelovedon',
 'greatescapeifancythebridgebutneedsherlagerseeyoutomo',
 'yesitcompletelyinoutofformclarkalsoutterwast',
 'sirineedaxisbankaccountnoandbankaddress',
 'hmmmthksuregottimetohopardyacangofreeabtmuzcallutodiscussliao',
 'whattimeyoucomingdownlat',
 'bloodyhellcantbelieveyouforgotmysurnamemrillgiveuaclueitsspanishandbeginswithm',
 'wellimgonnafinishmybathnowhaveagoodfinenight',
 'letmeknowwhenyouvegotthemoneysocarloscanmakethecal',
 'ustillgoingtothemal',
 'turnsoutmyfriendsarestayingforthewholeshowandwontbebacktilltgtsofeelfreetogoaheadandsmokethatltgtworth',
 'textherifshedoesntreplyletmeknowsoicanhaveherlogin',
 'hiyoujustspoketomaneeshavwedliketoknowifyouweresatisfiedwiththeexperiencereplytollfreewithyesorno',
 'youliftedmyhopeswiththeofferofmoneyiaminneedespeciallywhentheendofthemonthapproachesandithurtsmystudyinganywayshaveagrweekend',
 'lolnoucantrustm',
 'okiamagentlemanandwilltreatyouwithdignityandrespect',
 'hewillyouguysclos',
 'goingonnothinggreatby',
 'hellohandsomeareyoufindingthatjobnotbeinglazyworkingtowardsgettingbackthatnetformummywheresmyboytoynowdoeshemissm',
 'hahaawesomebethereinaminut',
 'pleasecallourcustomerservicerepresentativeonfreephonebetweenampmasyouhavewonaguaranteedcashorpr',
 'haveyougotxmasradiotimesifnotiwillgetitnow',
 'ijusreachedhomeigobathefirstbutmysisusingnettelluwhenshefinishesk',
 'areyouuniqueenoughfindoutfromthaugustwwwareyouuniquecouk',
 'imsorryivejoinedtheleagueofpeoplethatdontkeepintouchyoumeanagreatdealtomeyouhavebeenafriendatalltimesevenatgreatpersonalcostdohaveagreatweek',
 'hifinallyicompletedthecours',
 'itwillstoponitselfihoweversuggestshestayswithsomeonethatwillbeabletogiveorsforeverystool',
 'howareyoudoinghopeyouvesettledinforthenewschoolyearjustwishinyouagrday',
 'gudmrngdearhavaniceday',
 'didugotthatpersonsstori',
 'isyourhamsterdeadheysotmrimeetyouatpmorchardmrt',
 'hiitskatehowisyoureveningihopeicanseeyoutomorrowforabitbutihavetobloodybabyjontettxtbackifucanxxx',
 'founditencltgtwhereyouat',
 'isentyoultgtbuck',
 'hellodarlinivefinishedcollegenowsotxtmewhenufinishifucanlovekatexxx',
 'youraccounthasbeenrefilledsuccessfullybyinrltdecimalgtyourkeralacircleprepaidaccountbalanceisrsltdecimalgtyourtransactionidiskrltgt',
 'goodmorningsleepingga',
 'ucallmealteratok',
 'sayuntillikedatidunbuyericssonosocannotoredilar',
 'asienteredmycabinmypasaidhappybdaybossifeltspecialsheaskdmelunchafterlunchsheinvitedmetoherapartmentwewentther',
 'aightyodatsstraightdogg',
 'youpleasegiveusconnectiontodayitselfbeforeltdecimalgtorrefundthebil',
 'bothishootbigloadssogetreadi',
 'whatsupbruvhopeyouhadagreatbreakdohavearewardingsemest',
 'homesowecanalwayschat',
 'kkgoodstudywel',
 'yuphow_noeleh',
 'soundsgreatareyouhomenow',
 'finallythematchheadingtowardsdrawasyourpredict',
 'tiredihaventsleptwellthepastfewnight',
 'easyahsengotselectedmeansitsgood',
 'ihavetotakeexamwithmarch',
 'yeahyoushouldithinkyoucanuseyourgtatmnowtoregisternotsurebutiftheresanywayicanhelpletmeknowbutwhenyoudobesureyouarereadi',
 'oknoprobtakeurtim',
 'thereisoscalledubanduwhichwillrunwithoutinstallinginharddiskyoucanusethatostocopytheimportantfilesinsystemandgiveittorepairshop',
 'sorryillcalllat',
 'usaylehofcoursenothinghappenlarnotsayvromanticjusabitonlylorithkenitescenerynotsoniceleh',
 'newmobilesfrommustgotxtnokiatonocollectyourstodayfromonlywwwtcbizoptoutgbpmtmsg',
 'wouldreallyappreciateifyoucallmejustneedsomeonetotalkto',
 'willumeeturdreampartnersoonisurcareeroffaflyngstartfindoutfreetxthorofollowedbyurstarsigneghoroari',
 'heycompanyelamapomudyadhu',
 'lifeismorestrictthanteacherbcozteacherteacheslessonampthenconductsexambutlifefirstconductsexamampthenteacheslessonshappymorn',
 'deargoodmorningnowonlyiamup',
 'getdowningandhipuramandwalktocrosscutroadrightsideltgtstreetroadandturnatfirstright',
 'dearwearegoingtoourrubberplac',
 'sorrybatterydiedyeahimher',
 'yesheretvisalwaysavailableinworkplac',
 'textmeetsomeonesexytodayucanfindadateorevenflirtitsuptoujoinjustpreplywithnameageegsammsgrecdthirtyeightp',
 'ihaveprinteditohsoltgtcomeupstair',
 'orillbealittlecloserlikeatthebusstoponthesamestreet',
 'whereareyouwhenwilyoureachher',
 'newtheoryargumentwinsdsituationbutlosesthepersonsodontarguewithurfriendsjustkickthemampsayimalwayscorrect',
 'uhaveasecretadmirerwhoislookingmakecontactwithufindoutwhotheyrrevealwhothinksursospecialcallon',
 'tomarrowfinalhearingonmylaptopcasesoic',
 'pleassssssseeeeeetelmevaventdonesportsx',
 'okaynonojustshiningonthatwasmeanttobesigningbutthatsoundsbett',
 'althoughitoldudatimintobaigfacewatchesnowbutireallylikeewatchugavecositsfruthanxeverythingdatuvedonetodayimtouch',
 'udontrememberthatoldcommerci',
 'toolateisaidihavethewebsiteididntihaveordonthavetheslipp',
 'iaskedyoutocallhimnowok',
 'kalliswontbatinndin',
 'itdidntworkagainohokgoodnightthenillfixandhaveitreadybythetimeyouwakeupyouareverydearlymissedhaveagoodnightsleep',
 'congratulationsurawardedofcdvouchersorgiftguaranteedfreeentrywklydrawtxtmusictotncswwwldewcomwinppmxag',
 'ranjithcaldrpddeerajanddeepakminhold',
 'wenurlovablebcumsangrywidudnttakeitseriouslycozbeingangryisdmostchildishntruewayofshowingdeepaffectioncarenluvkettodamandahavenicedayda',
 'whatyoudoinghowarey',
 'upswhichisdaysalsoandtheshippingcompanythattakeswkstheotherwayisuspswhichtakesaweekbutwhenitgetstolagyoumayhavetobribeniposttogetyourstuff',
 'imbacklemmeknowwhenyourereadi',
 'dontnecessarilyexpectittobedonebeforeyougetbackthoughbecauseimjustnowheadinout',
 'mmmsoyummybabenicejolttothesuzi',
 'whereareyouloverineedy',
 'wetriedtocontactyoureyourreplytoourofferofavideohandsetanytimenetworksminsunlimitedtextcamcorderreplyorcallnow',
 'imparkednexttoaminiwhenareyoucomingintodaydoyouthink',
 'yup',
 'anywayimgoingshoppingonmyownnowcosmysisnotdoneyetdundisturbuliao',
 'mynoinlutonringmeifuraroundh',
 'heyiamreallyhornywanttochatorseemenakedtexthottotextchargedatpmtounsubscribetextstop',
 'whyyoudintcomewithu',
 'samewanaplanatripsometmethen',
 'notsureyetstilltryingtogetaholdofhim',
 'urringtoneservicehaschangedfreecreditsgotoclubmobilescomtochoosecontentnowstoptxtclubstoptopwkclubpoboxmkwt',
 'theevoijusthadtodownloadflashjeal',
 'ringtoneclubgettheuksingleschartonyourmobileeachweekandchooseanytopqualityringtonethismessageisfreeofcharg',
 'cometomuweresortingoutournarcoticssitu',
 'nighthasendedforanotherdaymorninghascomeinaspecialwaymayyousmilelikethesunnyraysandleavesyourworriesatthebluebluebay',
 'hmvbonusspecialpoundsofgenuinehmvvoucherstobewonjustanswereasyquestionsplaynowsendhmvtomoreinfowwwpercentrealcom',
 'usfiguessmightaswelltakecar',
 'noobjectionmybfnotcom',
 'thanx',
 'tellrobtomackhisgfinthetheat',
 'awesomeillseeyouinabit',
 'justsentitsowhattypeoffooddoyoulik',
 'alldoneallhandedincelebrationsinfullswingyet',
 'yougotcalledatool',
 '\\wenumisssomeon',
 'okiaskedformoneyhowfar',
 'oki',
 'yeahithinkmyusualguysstillpassedoutfromlastnightifyougetaholdofanybodyletmeknowandillthrowdown',
 'kimightcomebytonightthenifmyclassletsoutearli',
 'ok',
 'hibabyimcruisinwithmygirlfriendwhatruupgivemeacallinandhourathomeifthatsalrightorfonemeonthisfonenowlovejennyxxx',
 'mylifemeansalottomenotbecauseilovemylifebutbecauseilovethepeopleinmylifetheworldcallsthemfriendsicallthemmyworldg',
 'dearshallmailtonitebusyinthestreetshallupdateyoutonitethingsarelookingokvarunnathuedukkukayeerakshaollubutagoodoneinrealsens',
 'heyyoutoldyournametogauthamah',
 'hafufoundhimifeelsostupiddavcamwaswork',
 'oopsgotthatbit',
 'areyouthismuchbuzi',
 'iaccidentallydeletedthemessageresendpleas',
 'tmobilecustomeryoumaynowclaimyourfreecameraphoneupgradeapaygosimcardforyourloyaltycallonofferendsthfebtcsappli',
 'unlessitsasituationwhereyougogurlwouldbemoreappropri',
 'hurtmeteasememakemecrybutintheendofmylifewhenidieplzkeeponeroseonmygraveandsaystupidimissuhaveanicedaybslvyl',
 'icantpickthephonerightnowplssendamessag',
 'needacoffeeruntomocantbelieveitsthattimeofweekalreadi',
 'awesomeirememberthelasttimewegotsomebodyhighforthefirsttimewithdieselv',
 'shitthatisreallyshockingandscarycantimagineforaseconddefupfornightoutdouthinkthereissomewhereicouldcrashfornightsaveontaxi',
 'ohandbythewayyoudohavemorefoodinyourfridgewanttogooutforamealtonight',
 'heisawomdarfullactor',
 'smsacblinddateuroddsismfromaberdeenunitedkingdomcheckhimouthttpimgsmsacwicmbcktzrnoblinddatessendhid',

In [ ]:
### create the bag of words with 

from sklearn.feature_extraction.text import CountVectorizer
# for Bianry bag of words enable bianary = True
CountVectorizer = CountVectorizer(max_features=100,binary= True)

In [42]:
CountVectorizer.fit_transform(corpus).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [43]:
X = CountVectorizer.fit_transform(corpus).toarray()

In [44]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [45]:
X.shape

(5572, 100)

In [46]:
## Code with Lemmatization:

In [47]:
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\FINRISE\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\FINRISE\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [48]:
lemmatizetion = WordNetLemmatizer()

In [49]:
stop_words = set(stopwords.words('english'))

In [50]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [54]:
corpus = []
for i in range(0,len(messages)):
    review = re.sub('[^a-zA-Z]', ' ',messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [lemmatizetion.lemmatize(word) for word in review if word not in stopwords.words('english')]
    review = ''.join(review)
    corpus.append(review)

In [58]:
Vectorizer= CountVectorizer(max_features=100,binary=True)
X = Vectorizer.fit_transform(corpus).toarray()

In [59]:
print('shape of BoW:',X.shape)

shape of BoW: (5572, 100)

In [72]:
#Snowball Stemmer Setup

from nltk.stem.snowball import SnowballStemmer

In [61]:
SnowballStemmer  = SnowballStemmer('english')

In [62]:
stop_wordio = set(stopwords.words('english'))

In [63]:
stop_wordio

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [71]:
corpus = []
for i in range (0,len(messages)):
    review = re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review = review.lower()
    review = review.split()
    review =  [SnowballStemmer.stem(word) for word in review if word not in stop_wordio]
    review = ''.join(review)
    review = corpus.append(review)

In [73]:
# Create Binary Bag of Words
CountVectorizer(max_features=100,binary=True)

CountVectorizer(binary=True, max_features=100)

In [74]:
vectorizer  = CountVectorizer(max_features=100,binary=True)

In [75]:
vectorizer.fit_transform(corpus).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [76]:
X = vectorizer.fit_transform(corpus).toarray()

In [77]:
X.shape

(5572, 100)

In [78]:
print("Shap Of BoW:" ,X.shape)

Shap Of BoW: (5572, 100)