In [ ]:
# # one hot encoding
# # One-Hot Encoding is a method used to convert categorical variables into numerical format so they can be used in machine learning models.
# ✅ Why do we need it?
# Machine learning algorithms cannot directly process text labels like "red", "blue", or "green". They need numerical values.
# # If we just assign numbers (e.g., red=1, blue=2, green=3), the model might think green > blue > red, which is wrong because these categories have no inherent order.

In [ ]:
# D1 the food is good
# D2 the food is bad
# D3 pizza is amazing

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

In [3]:
# Documents with IDs
docs = {
    "D1": "the food is good",
    "D2": "the food is bad",
    "D3": "pizza is amazing"
}

In [4]:
docs

{'D1': 'the food is good', 'D2': 'the food is bad', 'D3': 'pizza is amazing'}

In [5]:
# Extract sentences and labels
docs.keys()

dict_keys(['D1', 'D2', 'D3'])

In [6]:
list(docs.keys())

['D1', 'D2', 'D3']

In [7]:
labels = list(docs.keys())

In [8]:
labels

['D1', 'D2', 'D3']

In [9]:
docs.values()

dict_values(['the food is good', 'the food is bad', 'pizza is amazing'])

In [10]:
list(docs.values())

['the food is good', 'the food is bad', 'pizza is amazing']

In [11]:
senetceon = list(docs.values())

In [12]:
senetceon

['the food is good', 'the food is bad', 'pizza is amazing']

In [13]:
# Create the one-hot encoded matrix
CountVectorizer(binary=True)

CountVectorizer(binary=True)

In [14]:
vectorizer = CountVectorizer(binary=True)

In [15]:
vectorizer.fit_transform(senetceon)

<3x7 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [16]:
one_hot_encoding = vectorizer.fit_transform(senetceon)

In [17]:
# Create a DataFrame with feature names as columns and labels as index
pd.DataFrame(one_hot_encoding.toarray(),columns=vectorizer.get_feature_names_out(),index=labels)

    amazing  bad  food  good  is  pizza  the
D1        0    0     1     1   1      0    1
D2        0    1     1     0   1      0    1
D3        1    0     0     0   1      1    0

In [18]:
df = pd.DataFrame(one_hot_encoding.toarray(),columns=vectorizer.get_feature_names_out(),index=labels)

In [19]:
df

    amazing  bad  food  good  is  pizza  the
D1        0    0     1     1   1      0    1
D2        0    1     1     0   1      0    1
D3        1    0     0     0   1      1    0

In [22]:
# Tokenize and Create Vocabulary

all_words = set()
for text in docs.values():
    all_words.update(text.split())

In [23]:
# Sort for consistent order
sorted(all_words)

['amazing', 'bad', 'food', 'good', 'is', 'pizza', 'the']

In [24]:
vocab = sorted(all_words)

In [25]:

{word:i for i, word in enumerate(vocab)}

{'amazing': 0, 'bad': 1, 'food': 2, 'good': 3, 'is': 4, 'pizza': 5, 'the': 6}

In [26]:
word_to_index = {word:i for i, word in enumerate(vocab)}

In [30]:
print(word_to_index)

{'amazing': 0, 'bad': 1, 'food': 2, 'good': 3, 'is': 4, 'pizza': 5, 'the': 6}

In [31]:
print("vocabulary:",vocab)

vocabulary: ['amazing', 'bad', 'food', 'good', 'is', 'pizza', 'the']

In [32]:
#Document-level One-Hot Encoding
print("n\Document-level One-Hot Encoding:")
doc_encoding = {}
for doc_id, text in docs.items():
    vector = [0] * len(vocab)
    for word in text.split():
        vector[word_to_index[word]] = 1
    doc_encoding[doc_id] = vector
    print(f"{doc_id}:{vector}")

n\Document-level One-Hot Encoding:
D1:[0, 0, 1, 1, 1, 0, 1]
D2:[0, 1, 1, 0, 1, 0, 1]
D3:[1, 0, 0, 0, 1, 1, 0]

In [33]:
# Word-level One-Hot Encoding

print("n\Document-level One-Hot Encoding:")
for word in vocab:
    vector = [0] * len(vocab)
    vector[word_to_index[word]] = 1
    print(f"{word}:{vector}")

n\Document-level One-Hot Encoding:
amazing:[1, 0, 0, 0, 0, 0, 0]
bad:[0, 1, 0, 0, 0, 0, 0]
food:[0, 0, 1, 0, 0, 0, 0]
good:[0, 0, 0, 1, 0, 0, 0]
is:[0, 0, 0, 0, 1, 0, 0]
pizza:[0, 0, 0, 0, 0, 1, 0]
the:[0, 0, 0, 0, 0, 0, 1]